spring.application.name=smart-mobility-front
server.port=8090

# URL de la Gateway
gateway.url=http://localhost:8765

# Configuration Thymeleaf
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false
